name: Daily Air Quality Data Pipeline

on:
  schedule:
    # Runs at 5:00 AM UTC every day
    - cron: '0 5 * * *'

  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run air quality pipeline
      timeout-minutes: 55
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        API_CONCURRENCY: "20"
        DB_CONCURRENCY: "5"
        TASK_CONCURRENCY: "30"
        INSERT_BATCH_SIZE: "200"
      run: python pipeline.py

    - name: Upload logs (if any)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-logs-${{ github.run_number }}
        path: |
          *.log
          /tmp/logs/
        retention-days: 7
